[package]
name = "async-crawler"
version = "0.1.0"
authors = ["Florian Gilcher <florian.gilcher@ferrous-systems.com>", "Johann <git@johann-hofmann.com>"]
edition = "2018"

[dependencies]
async-std = { path = "../async-std" }
surf = { path = "../surf" }
html5ever = "0.24.0"
